[package]
name = "evmelf"
version = "0.1.0"
authors = ["Jake Lang <jak3lang@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
elf = "0.0.10"
log = "0.4.8"
env_logger = "0.6.2"
serde_json = "1.0"
hex = "0.4.0"
